// TestAgainstMatlab.c
// Reads matlabcompare.txt generated by matlabcompare.m. The text data format is
// documented at the top of tests/matlabcompare.m.
#include <math.h>
#include <float.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "VarmaUtilities.h"
#include "ExtraUtil.h"
#include "error.h"
#include "xCheck.h"
#include "printX.h"
#include "Tests.h"
#include "varmapack.h"
#include "DebugUtil.h"
#include "FromMatlab.h"

static int getdim(FILE *fid, char *base, int k) {
  char name[32];
  double scalar = 0;
  bool ok;
  STRSETF(name, "%s%d", base, k);
  ok = DoubleFromMatlab(fid, name, &scalar);
  xCheck(ok);
  return scalar;
}

static double sim_tol(int n, double rho) {
  double stability = rho < 1 ? 1/(1 - rho) : 1/DBL_EPSILON;
  // This eps multiplier allows for array size and stationarity sensitivity:
  // 10*sqrt(n)/(1-rho)^2. The form and constant were chosen by trial and error.
  return 10*DBL_EPSILON*sqrt((double)(n > 0 ? n : 1))*stability*stability;
}

static void check_norm_relative(char *what, int icase, double diff, double tol) {
  if (diff >= tol) {
    fprintf(stderr, "%s case %d: diff %.3e, tol %.3e\n", what, icase, diff, tol);
  }
  xCheck(diff < tol);
}

static bool pathwise_conditional_check(int icase) {
  return icase != 7;
}

bool TestAgainstMatlab(void) {
  // Bring in MATLAB reference data
  int n, p, q, r, pk, qk, rk, h, ncases, nMs, acvfMaxlag;
  double *cases = 0, *Ms = 0, *A = 0, *B = 0, *Sig = 0, *mu = 0, *x0 = 0;
  double *Gamma = 0;
  double condR, tol, rhoMatlab, rhoC;
  bool ok;
  char name[64] = {0};
  char comparefile[] = "matlabcompare.txt";
  FILE *fid = fopen(comparefile, "r");
  ASSERT(fid != 0, "File %s cannot be read", comparefile);
  ok = IntFromMatlab(fid, "#cases", &ncases);
  ok &= IntFromMatlab(fid, "#Ms", &nMs);
  ok &= IntFromMatlab(fid, "n", &n);
  xCheck(ok && ncases < 1000);
  ASSERT(ALLOC(cases, ncases), "allocation failed");
  ASSERT(ALLOC(Ms, nMs), "allocation failed");
  ok = MatrixFromMatlab(fid, "cases", cases, 1, ncases);
  ok &= MatrixFromMatlab(fid, "Ms", Ms, 1, nMs);
  xCheck(ok);

  // Loop over cases
  for (int k = 0; k < ncases; k++) {
    int icase = cases[k];
    int label = icase + 1;
    xCheck(0 <= icase && icase < 100);
    
    // Get dimensions from Matlab file
    p = getdim(fid, "p", label);
    q = getdim(fid, "q", label);
    r = getdim(fid, "r", label);
    h = imax(p, q);

    // Get condition number, set tolerance
    STRSETF(name, "condR-%d", icase);
    ok = DoubleFromMatlab(fid, name, &condR);
    xCheck(ok);
    tol = 5e-16;

    // Get starting vector
    ASSERT(ALLOC(x0, r*h > 0 ? r*h : 1), "allocation failed");
    STRSETF(name, "x0%d", label);
    ok = MatrixFromMatlab(fid, name, x0, r, h);
    xCheck(ok);
    ASSERT(ALLOC(mu, r), "allocation failed");
    STRSETF(name, "mu%d", label);
    ok = MatrixFromMatlab(fid, name, mu, r, 1);
    xCheck(ok);
    STRSETF(name, "specrad-%d", icase);
    ok = DoubleFromMatlab(fid, name, &rhoMatlab);
    xCheck(ok);
    STRSETF(name, "acvfMaxlag-%d", icase);
    ok = IntFromMatlab(fid, name, &acvfMaxlag);
    xCheck(ok);

    // Set additional message to testcase number
    printI("TESTCASE NUMBER", icase);
    char addmsg[32];
    snprintf(addmsg, 32, "varmapack_testcase number %2d", icase);
    xCheckAddMsg(addmsg);

    // Query testcase dimensions and check them
    STRSET(name, "");
    ok = varmapack_testcase(0, 0, 0, name, &pk, &qk, &rk, &icase, 0, stderr);
    xCheck(ok);
    xCheck(pk == p);
    xCheck(qk == q);
    xCheck(rk == r);
    xCheck(h <= n);

    // Allocate and fetch actual testcase coefficients
    int r2 = r*r;
    ASSERT(ALLOC(A, r2*(p > 0 ? p : 1)), "allocation failed");
    ASSERT(ALLOC(B, r2*(q > 0 ? q : 1)), "allocation failed");
    ASSERT(ALLOC(Sig, r2), "allocation failed");
    STRSET(name, "");
    ok = varmapack_testcase(A, B, Sig, name, &p, &q, &r, &icase, 0, stderr);
    xCheck(ok);
    rhoC = varmapack_specrad(A, r, p);
    xCheck(fabs(rhoC - rhoMatlab) < 1e-12);
    ASSERT(ALLOC(Gamma, r2*(acvfMaxlag+1)), "allocation failed");
    ok = varmapack_acvf(A, B, Sig, p, q, r, Gamma, acvfMaxlag);
    xCheck(ok);

    // Compare A, B, Sig against MATLAB reference
    double diffA, diffB, diffSig, diffGamma;
    
    STRSETF(name, "A%d", label);   CompareWithMatlab(fid, name, A, r, r*p, &diffA);
    STRSETF(name, "B%d", label);   CompareWithMatlab(fid, name, B, r, r*q, &diffB);
    STRSETF(name, "Sig%d", label); CompareWithMatlab(fid, name, Sig, r, r, &diffSig);
    STRSETF(name, "Gamma-%d", icase);
    ok = CompareWithMatlab(fid, name, Gamma, r*r, acvfMaxlag+1, &diffGamma);
    xCheck(ok);
    xCheck(diffA < tol && diffB < tol && diffSig < tol && diffGamma < 5e-15);

    // Simulate with varmapack_sim and compare the simulated series with Matlab's
    for (int j=0; j<(int)nMs; j++) {
      int M = Ms[j];
      double *X = 0, *E = 0, *X0 = 0, *E0 = 0;
      double *Xmu = 0, *Emu = 0, *X0mu = 0, *E0mu = 0;
      double *AutoML = 0, *AutoC = 0;
      bool sim_ok;
      h = imax(p, q);
    
      ASSERT(ALLOC(X, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0, r*n*M), "allocation failed");
      ASSERT(ALLOC(Xmu, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0mu, r*n*M), "allocation failed");
      ASSERT(ALLOC(E, r*n*M), "allocation failed");
      ASSERT(ALLOC(E0, r*n*M), "allocation failed");
      ASSERT(ALLOC(Emu, r*n*M), "allocation failed");
      ASSERT(ALLOC(E0mu, r*n*M), "allocation failed");
      ASSERT(ALLOC(AutoML, r2*n), "allocation failed");
      ASSERT(ALLOC(AutoC, r2*n), "allocation failed");
      randompack_rng *rng = randompack_create(0);
      randompack_seed(42, 0, 0, rng);
      printM("A", A, r, r*p);
      printM("B", B, r, r*q);
      printM("Sig", Sig, r, r);
      randompack_seed(42, 0, 0, rng);
      varmapack_sim(A, B, Sig, 0, p, q, r, n, M, 0, 0, rng, X, E, &sim_ok);
      randompack_seed(42, 0, 0, rng);
      varmapack_sim(A, B, Sig, 0, p, q, r, n, M, x0, h, rng, X0, E0, &sim_ok);
      randompack_seed(42, 0, 0, rng);
      varmapack_sim(A, B, Sig, mu, p, q, r, n, M, 0, 0, rng, Xmu, Emu, &sim_ok);
      randompack_seed(42, 0, 0, rng);
      varmapack_sim(A, B, Sig, mu, p, q, r, n, M, x0, h, rng, X0mu, E0mu,
                    &sim_ok);
      varmapack_autocov("N", "ML", r, n, X, n-1, AutoML);
      varmapack_autocov("N", "C", r, n, X, n-1, AutoC);
      printM("X0", X0, r, n*M);
      xCheck(sim_ok == 1);
      // Compare E and X
      
      double diffE, diffX, diffE0, diffX0, diffEmu, diffXmu, diffE0mu, diffX0mu;
      double diffAutoML, diffAutoC;
      STRSETF(name, "AutoML%d-%d", M, icase);
      ok = CompareWithMatlab(fid, name, AutoML, r*r, n, &diffAutoML);
      STRSETF(name, "AutoC%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, AutoC, r*r, n, &diffAutoC);
      STRSETF(name, "E%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E, r*n, M, &diffE);
      STRSETF(name, "X%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X, r*n, M, &diffX);
      STRSETF(name, "E0%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E0, r*n, M, &diffE0);
      STRSETF(name, "X0%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0, r*n, M, &diffX0);
      STRSETF(name, "Emu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Emu, r*n, M, &diffEmu);
      STRSETF(name, "Xmu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Xmu, r*n, M, &diffXmu);
      STRSETF(name, "E0mu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E0mu, r*n, M, &diffE0mu);
      STRSETF(name, "X0mu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0mu, r*n, M, &diffX0mu);
      ASSERT(ok, "error comparing with Matlab");
      printD(">>> diffX", diffX);
      printD(">>> diffE", diffE);
      printD(">>> diffX0", diffX0);
      printD(">>> diffE0", diffE0);
      printD(">>> diffXmu", diffXmu);
      printD(">>> diffEmu", diffEmu);
      printD(">>> diffX0mu", diffX0mu);
      printD(">>> diffE0mu", diffE0mu);
      double simTol = sim_tol(r*n*M, rhoC);
      double autoTol = sim_tol(r2*n, rhoC);
      printD(">>> condR", condR);
      printD(">>> simulation tolerance", simTol);
      printD(">>> autocov tolerance", autoTol);
      check_norm_relative("E", icase, diffE, simTol);
      check_norm_relative("X", icase, diffX, simTol);
      check_norm_relative("AutoML", icase, diffAutoML, autoTol);
      check_norm_relative("AutoC", icase, diffAutoC, autoTol);
      check_norm_relative("Emu", icase, diffEmu, simTol);
      check_norm_relative("Xmu", icase, diffXmu, simTol);
      if (pathwise_conditional_check(icase)) {
        check_norm_relative("E0", icase, diffE0, simTol);
        check_norm_relative("X0", icase, diffX0, simTol);
        check_norm_relative("E0mu", icase, diffE0mu, simTol);
        check_norm_relative("X0mu", icase, diffX0mu, simTol);
      }

      // Free memory
      FREE(AutoC);
      FREE(AutoML);
      FREE(E0mu);
      FREE(X0mu);
      FREE(Emu);
      FREE(Xmu);
      FREE(E0);
      FREE(X0);
      FREE(E);
      FREE(X);
      randompack_free(rng);
    }
    FREE(A);
    FREE(B);
    FREE(Sig);
    FREE(Gamma);
    FREE(mu);
    FREE(x0);
    xCheckAddMsg("");
  }
  FREE(cases);
  FREE(Ms);
  fclose(fid);
  return true;
}
