// TestAgainstMatlab.c
// Reads matlabcompare.txt generated by matlabcompare.m. The text data format is
// documented at the top of tests/matlabcompare.m.
#include <math.h>
#include <float.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "VarmaUtilities.h"
#include "ExtraUtil.h"
#include "error.h"
#include "xCheck.h"
#include "printX.h"
#include "Tests.h"
#include "varmapack.h"
#include "FromMatlab.h"

static int getdim(FILE *fid, char *base, int k) {
  char name[32];
  double scalar = 0;
  bool ok;
  STRSETF(name, "%s%d", base, k);
  ok = DoubleFromMatlab(fid, name, &scalar);
  xCheck(ok);
  return scalar;
}

static double sim_tol(int n, double rho) {
  double stability = rho < 1 ? 1/(1 - rho) : 1/DBL_EPSILON;
  // This eps multiplier allows for array size and stationarity sensitivity:
  // 150*sqrt(n)/(1-rho)^2. The form and constant were chosen by trial and error.
  return 150*DBL_EPSILON*sqrt((double)(n > 0 ? n : 1))*stability*stability;
}

static void check_norm_relative(char *what, int icase, double diff, double tol) {
  if (diff >= tol) {
    fprintf(stderr, "%s case %d: diff %.3e, tol %.3e\n", what, icase, diff, tol);
  }
  xCheck(diff < tol);
}

static bool pathwise_conditional_check(int icase) {
  return icase != 7;
}

static bool compare_reduced_m(FILE *fid, int n) {
  int nReducedCases, reducedM;
  int *reducedCases = 0;
  bool ok;
  varmapack_error error;
  char name[64] = {0};
  ok = IntFromMatlab(fid, "#reducedCases", &nReducedCases);
  ok &= IntFromMatlab(fid, "reducedM", &reducedM);
  xCheck(ok && nReducedCases > 0);
  ASSERT(ALLOC(reducedCases, nReducedCases), "allocation failed");
  ok = IntVecFromMatlab(fid, "reducedCases", reducedCases, nReducedCases);
  xCheck(ok);
  for (int k=0; k<nReducedCases; k++) {
    int icase = reducedCases[k];
    int label = icase + 1;
    int p = 0, q = 0, r = 0;
    int h, r2;
    double *A = 0, *B = 0, *Sig = 0, *mu = 0, *StartX0 = 0;
    double *X = 0, *E = 0, *X0 = 0, *E0 = 0;
    double *Xmu = 0, *Emu = 0, *X0mu = 0, *E0mu = 0;
    double *XT = 0, *AutoMLT = 0, *AutoCT = 0;
    double diffE, diffX, diffE0, diffX0, diffEmu, diffXmu, diffE0mu, diffX0mu;
    double diffAutoMLT, diffAutoCT, rhoC, simTol, autoTol;
    randompack_rng *rng = 0;
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &p, &q, &r, 0, 0, 0, 0);
    xCheck(!error);
    h = imax(p, q);
    r2 = r*r;
    snprintf(name, 64, "reduced M=%d varmapack_testcase number %2d", reducedM, icase);
    xCheckAddMsg(name);
    ASSERT(ALLOC(A, r2*(p > 0 ? p : 1)), "allocation failed");
    ASSERT(ALLOC(B, r2*(q > 0 ? q : 1)), "allocation failed");
    ASSERT(ALLOC(Sig, r2), "allocation failed");
    ASSERT(ALLOC(StartX0, r*h > 0 ? r*h : 1), "allocation failed");
    ASSERT(ALLOC(mu, r), "allocation failed");
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &p, &q, &r, A, B, Sig, 0);
    xCheck(!error);
    STRSETF(name, "X0%d", label);
    ok = MatrixFromMatlab(fid, name, StartX0, r, h);
    STRSETF(name, "mu%d", label);
    ok &= MatrixFromMatlab(fid, name, mu, r, 1);
    xCheck(ok);
    ASSERT(ALLOC(X, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(X0, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(Xmu, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(X0mu, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(E, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(E0, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(Emu, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(E0mu, r*n*reducedM), "allocation failed");
    ASSERT(ALLOC(XT, n*r), "allocation failed");
    ASSERT(ALLOC(AutoMLT, r2*n), "allocation failed");
    ASSERT(ALLOC(AutoCT, r2*n), "allocation failed");
    rng = randompack_create(0);
    randompack_seed(42, 0, 0, rng);
    error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, reducedM, 0, 0, 1, X, E, rng);
    xCheck(!error);
    randompack_seed(42, 0, 0, rng);
    error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, reducedM, StartX0, h, 1, X0, E0, rng);
    xCheck(!error);
    randompack_seed(42, 0, 0, rng);
    error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, reducedM, 0, 0, 1, Xmu, Emu, rng);
    xCheck(!error);
    randompack_seed(42, 0, 0, rng);
    error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, reducedM, StartX0, h, 1, X0mu, E0mu, rng);
    xCheck(!error);
    copytranspose(r, n, X + r*n, r, XT, n);
    error = varmapack_autocov("T", "ML", r, n, XT, n-1, AutoMLT);
    xCheck(!error);
    error = varmapack_autocov("T", "C", r, n, XT, n-1, AutoCT);
    xCheck(!error);
    STRSETF(name, "RedAutoMLT%d-%d", reducedM, icase);
    ok = CompareWithMatlab(fid, name, AutoMLT, r*r, n, &diffAutoMLT);
    STRSETF(name, "RedAutoCT%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, AutoCT, r*r, n, &diffAutoCT);
    STRSETF(name, "RedE%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, E, r*n, reducedM, &diffE);
    STRSETF(name, "RedX%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, X, r*n, reducedM, &diffX);
    STRSETF(name, "RedE0%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, E0, r*n, reducedM, &diffE0);
    STRSETF(name, "RedX0%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, X0, r*n, reducedM, &diffX0);
    STRSETF(name, "RedEmu%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, Emu, r*n, reducedM, &diffEmu);
    STRSETF(name, "RedXmu%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, Xmu, r*n, reducedM, &diffXmu);
    STRSETF(name, "RedE0mu%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, E0mu, r*n, reducedM, &diffE0mu);
    STRSETF(name, "RedX0mu%d-%d", reducedM, icase);
    ok &= CompareWithMatlab(fid, name, X0mu, r*n, reducedM, &diffX0mu);
    ASSERT(ok, "error comparing reduced M with Matlab");
    rhoC = varmapack_specrad(A, r, p);
    simTol = sim_tol(r*n*reducedM, rhoC);
    autoTol = sim_tol(r2*n, rhoC);
    check_norm_relative("RedE", icase, diffE, simTol);
    check_norm_relative("RedX", icase, diffX, simTol);
    check_norm_relative("RedAutoMLT", icase, diffAutoMLT, autoTol);
    check_norm_relative("RedAutoCT", icase, diffAutoCT, autoTol);
    check_norm_relative("RedEmu", icase, diffEmu, simTol);
    check_norm_relative("RedXmu", icase, diffXmu, simTol);
    if (pathwise_conditional_check(icase)) {
      check_norm_relative("RedE0", icase, diffE0, simTol);
      check_norm_relative("RedX0", icase, diffX0, simTol);
      check_norm_relative("RedE0mu", icase, diffE0mu, simTol);
      check_norm_relative("RedX0mu", icase, diffX0mu, simTol);
    }
    FREE(AutoCT);
    FREE(AutoMLT);
    FREE(XT);
    FREE(E0mu);
    FREE(X0mu);
    FREE(Emu);
    FREE(Xmu);
    FREE(E0);
    FREE(X0);
    FREE(E);
    FREE(X);
    FREE(mu);
    FREE(StartX0);
    FREE(Sig);
    FREE(B);
    FREE(A);
    randompack_free(rng);
  }
  FREE(reducedCases);
  xCheckAddMsg("");
  return true;
}

static bool compare_rolling_matlab(void) {
  int n, p, q, r, h, ncases, nMs;
  double *cases = 0, *Ms = 0;
  double *A = 0, *B = 0, *Sig = 0, *mu = 0, *StartX0 = 0;
  bool ok;
  varmapack_error error;
  char name[64] = {0};
  char comparefile[] = "matlabcompare-rolling.txt";
  FILE *fid = fopen(comparefile, "r");
  ASSERT(fid != 0, "File %s cannot be read", comparefile);
  ok = IntFromMatlab(fid, "#cases", &ncases);
  ok &= IntFromMatlab(fid, "#Ms", &nMs);
  ok &= IntFromMatlab(fid, "n", &n);
  xCheck(ok && ncases < 1000);
  ASSERT(ALLOC(cases, ncases), "allocation failed");
  ASSERT(ALLOC(Ms, nMs), "allocation failed");
  ok = MatrixFromMatlab(fid, "cases", cases, 1, ncases);
  ok &= MatrixFromMatlab(fid, "Ms", Ms, 1, nMs);
  xCheck(ok);
  for (int k=0; k<ncases; k++) {
    int icase = cases[k];
    int label = icase + 1;
    int r2;
    double rhoC;
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &p, &q, &r, 0, 0, 0, 0);
    xCheck(!error);
    h = imax(p, q);
    r2 = r*r;
    ASSERT(ALLOC(A, r2*(p > 0 ? p : 1)), "allocation failed");
    ASSERT(ALLOC(B, r2*(q > 0 ? q : 1)), "allocation failed");
    ASSERT(ALLOC(Sig, r2), "allocation failed");
    ASSERT(ALLOC(StartX0, r*h > 0 ? r*h : 1), "allocation failed");
    ASSERT(ALLOC(mu, r), "allocation failed");
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &p, &q, &r, A, B, Sig, 0);
    xCheck(!error);
    rhoC = varmapack_specrad(A, r, p);
    STRSETF(name, "X0%d", label);
    ok = MatrixFromMatlab(fid, name, StartX0, r, h);
    STRSETF(name, "mu%d", label);
    ok &= MatrixFromMatlab(fid, name, mu, r, 1);
    xCheck(ok);
    for (int j=0; j<nMs; j++) {
      int M = Ms[j];
      double *X = 0, *X0 = 0, *Xmu = 0, *X0mu = 0;
      double diffX, diffX0, diffXmu, diffX0mu;
      // Rolling MA uses split products, so allow a small extra roundoff margin.
      double simTol = 5*sim_tol(r*n*M, rhoC);
      randompack_rng *rng = randompack_create(0);
      ASSERT(ALLOC(X, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0, r*n*M), "allocation failed");
      ASSERT(ALLOC(Xmu, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0mu, r*n*M), "allocation failed");
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, M, 0, 0, 1, X, 0, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, M, StartX0, h, 1, X0, 0, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, M, 0, 0, 1, Xmu, 0, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, M, StartX0, h, 1, X0mu, 0, rng);
      xCheck(!error);
      STRSETF(name, "X%d-%d", M, icase);
      ok = CompareWithMatlab(fid, name, X, r*n, M, &diffX);
      STRSETF(name, "X0%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0, r*n, M, &diffX0);
      STRSETF(name, "Xmu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Xmu, r*n, M, &diffXmu);
      STRSETF(name, "X0mu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0mu, r*n, M, &diffX0mu);
      ASSERT(ok, "error comparing rolling simulation with Matlab");
      check_norm_relative("RollX", icase, diffX, simTol);
      check_norm_relative("RollXmu", icase, diffXmu, simTol);
      if (pathwise_conditional_check(icase)) {
        check_norm_relative("RollX0", icase, diffX0, simTol);
        check_norm_relative("RollX0mu", icase, diffX0mu, simTol);
      }
      FREE(X0mu);
      FREE(Xmu);
      FREE(X0);
      FREE(X);
      randompack_free(rng);
    }
    FREE(mu);
    FREE(StartX0);
    FREE(Sig);
    FREE(B);
    FREE(A);
  }
  FREE(Ms);
  FREE(cases);
  fclose(fid);
  return true;
}

static bool compare_varmax_matlab(FILE *fid, int n, double Ms[], int nMs) {
  int ncases, xMultiM;
  double *cases = 0;
  bool ok;
  varmapack_error error;
  char name[64] = {0};
  ok = IntFromMatlab(fid, "#xcases", &ncases);
  ok &= IntFromMatlab(fid, "xMultiM", &xMultiM);
  xCheck(ok && ncases > 0 && ncases < 1000);
  ASSERT(ALLOC(cases, ncases), "allocation failed");
  ok = MatrixFromMatlab(fid, "xcases", cases, 1, ncases);
  xCheck(ok);
  for (int k=0; k<ncases; k++) {
    int icase = cases[k];
    int p, q, s, r, h, r2;
    double *A = 0, *B = 0, *C = 0, *Sig = 0, *z = 0, *StartX0 = 0;
    double *zM = 0, *StartX0M = 0;
    double rhoC;
    STRSETF(name, "VARMAX testcase number %2d", icase);
    xCheckAddMsg(name);
    STRSETF(name, "xp%d", icase); ok = IntFromMatlab(fid, name, &p);
    STRSETF(name, "xq%d", icase); ok &= IntFromMatlab(fid, name, &q);
    STRSETF(name, "xs%d", icase); ok &= IntFromMatlab(fid, name, &s);
    STRSETF(name, "xr%d", icase); ok &= IntFromMatlab(fid, name, &r);
    STRSETF(name, "xh%d", icase); ok &= IntFromMatlab(fid, name, &h);
    xCheck(ok);
    r2 = r*r;
    ASSERT(ALLOC(A, r2*(p > 0 ? p : 1)), "allocation failed");
    ASSERT(ALLOC(B, r2*(q > 0 ? q : 1)), "allocation failed");
    ASSERT(ALLOC(C, r*(s > 0 ? s : 1)), "allocation failed");
    ASSERT(ALLOC(Sig, r2), "allocation failed");
    ASSERT(ALLOC(z, n), "allocation failed");
    ASSERT(ALLOC(StartX0, r*h), "allocation failed");
    ASSERT(ALLOC(zM, n*xMultiM), "allocation failed");
    ASSERT(ALLOC(StartX0M, r*h*xMultiM), "allocation failed");
    STRSETF(name, "xA%d", icase); ok = MatrixFromMatlab(fid, name, A, r, r*p);
    STRSETF(name, "xB%d", icase); ok &= MatrixFromMatlab(fid, name, B, r, r*q);
    STRSETF(name, "xC%d", icase); ok &= MatrixFromMatlab(fid, name, C, r, s);
    STRSETF(name, "xSig%d", icase); ok &= MatrixFromMatlab(fid, name, Sig, r, r);
    STRSETF(name, "xz%d", icase); ok &= MatrixFromMatlab(fid, name, z, 1, n);
    STRSETF(name, "xStartX0%d", icase); ok &= MatrixFromMatlab(fid, name, StartX0, r, h);
    STRSETF(name, "xzM%d-%d", xMultiM, icase);
    ok &= MatrixFromMatlab(fid, name, zM, n, xMultiM);
    STRSETF(name, "xStartX0M%d-%d", xMultiM, icase);
    ok &= MatrixFromMatlab(fid, name, StartX0M, r*h, xMultiM);
    xCheck(ok);
    rhoC = varmapack_specrad(A, r, p);
    for (int j=0; j<nMs; j++) {
      int M = Ms[j];
      double *X = 0, *E = 0, *XnoE = 0;
      double diffX, diffE, diffXnoE;
      double simTol = sim_tol(r*n*M, rhoC);
      randompack_rng *rng = randompack_create(0);
      ASSERT(ALLOC(X, r*n*M), "allocation failed");
      ASSERT(ALLOC(E, r*n*M), "allocation failed");
      ASSERT(ALLOC(XnoE, r*n*M), "allocation failed");
      randompack_seed(42, 0, 0, rng);
      error = varmapack_simx(A, B, C, Sig, z, 1, p, q, s, r, n, M, StartX0, h, 1,
                             X, E, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_simx(A, B, C, Sig, z, 1, p, q, s, r, n, M, StartX0, h, 1,
                             XnoE, 0, rng);
      xCheck(!error);
      STRSETF(name, "Xx%d-%d", M, icase);
      ok = CompareWithMatlab(fid, name, X, r*n, M, &diffX);
      STRSETF(name, "Ex%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E, r*n, M, &diffE);
      STRSETF(name, "XxNoE%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, XnoE, r*n, M, &diffXnoE);
      ASSERT(ok, "error comparing VARMAX with Matlab");
      check_norm_relative("Xx", icase, diffX, simTol);
      check_norm_relative("Ex", icase, diffE, simTol);
      check_norm_relative("XxNoE", icase, diffXnoE, simTol);
      FREE(XnoE);
      FREE(E);
      FREE(X);
      randompack_free(rng);
    }
    int M = xMultiM;
    double *X = 0, *E = 0;
    double diffX, diffE;
    double simTol = sim_tol(r*n*M, rhoC);
    randompack_rng *rng = randompack_create(0);
    ASSERT(ALLOC(X, r*n*M), "allocation failed");
    ASSERT(ALLOC(E, r*n*M), "allocation failed");
    randompack_seed(42, 0, 0, rng);
    error = varmapack_simx(A, B, C, Sig, zM, M, p, q, s, r, n, M, StartX0M, h, M,
                           X, E, rng);
    xCheck(!error);
    STRSETF(name, "XxM%d-%d", M, icase);
    ok = CompareWithMatlab(fid, name, X, r*n, M, &diffX);
    STRSETF(name, "ExM%d-%d", M, icase);
    ok &= CompareWithMatlab(fid, name, E, r*n, M, &diffE);
    ASSERT(ok, "error comparing VARMAX multipath with Matlab");
    check_norm_relative("XxM", icase, diffX, simTol);
    check_norm_relative("ExM", icase, diffE, simTol);
    FREE(E);
    FREE(X);
    randompack_free(rng);
    FREE(StartX0M);
    FREE(zM);
    FREE(StartX0);
    FREE(z);
    FREE(Sig);
    FREE(C);
    FREE(B);
    FREE(A);
  }
  FREE(cases);
  xCheckAddMsg("");
  return true;
}

bool TestAgainstMatlab(void) {
  // Bring in MATLAB reference data
  int n, p, q, r, pk, qk, rk, h, ncases, nMs, acvfMaxlag;
  double *cases = 0, *Ms = 0, *A = 0, *B = 0, *Sig = 0, *mu = 0, *muPath = 0;
  double *StartX0 = 0, *Gamma = 0, *Psi = 0, *Theta = 0;
  double tol, rhoMatlab, maRhoMatlab, rhoC, maRhoC;
  bool ok;
  varmapack_error error;
  char name[64] = {0};
  char comparefile[] = "matlabcompare.txt";
  FILE *fid = fopen(comparefile, "r");
  ASSERT(fid != 0, "File %s cannot be read", comparefile);
  ok = IntFromMatlab(fid, "#cases", &ncases);
  ok &= IntFromMatlab(fid, "#Ms", &nMs);
  ok &= IntFromMatlab(fid, "n", &n);
  xCheck(ok && ncases < 1000);
  ASSERT(ALLOC(cases, ncases), "allocation failed");
  ASSERT(ALLOC(Ms, nMs), "allocation failed");
  ok = MatrixFromMatlab(fid, "cases", cases, 1, ncases);
  ok &= MatrixFromMatlab(fid, "Ms", Ms, 1, nMs);
  xCheck(ok);

  // Loop over cases
  for (int k = 0; k < ncases; k++) {
    int icase = cases[k];
    int label = icase + 1;
    xCheck(0 <= icase && icase < 100);
    
    // Get dimensions from Matlab file
    p = getdim(fid, "p", label);
    q = getdim(fid, "q", label);
    r = getdim(fid, "r", label);
    h = imax(p, q);

    // Set tolerance for comparing testcase inputs.
    tol = 5e-16;

    // Get starting vector
    ASSERT(ALLOC(StartX0, r*h > 0 ? r*h : 1), "allocation failed");
    STRSETF(name, "X0%d", label);
    ok = MatrixFromMatlab(fid, name, StartX0, r, h);
    xCheck(ok);
    ASSERT(ALLOC(mu, r), "allocation failed");
    STRSETF(name, "mu%d", label);
    ok = MatrixFromMatlab(fid, name, mu, r, 1);
    xCheck(ok);
    ASSERT(ALLOC(muPath, 3*r), "allocation failed");
    STRSETF(name, "muPath%d", label);
    ok = MatrixFromMatlab(fid, name, muPath, r, 3);
    xCheck(ok);
    STRSETF(name, "specrad-%d", icase);
    ok = DoubleFromMatlab(fid, name, &rhoMatlab);
    xCheck(ok);
    STRSETF(name, "maSpecrad-%d", icase);
    ok = DoubleFromMatlab(fid, name, &maRhoMatlab);
    xCheck(ok);
    STRSETF(name, "acvfMaxlag-%d", icase);
    ok = IntFromMatlab(fid, name, &acvfMaxlag);
    xCheck(ok);

    // Set additional message to testcase number
    printI("TESTCASE NUMBER", icase);
    char addmsg[32];
    snprintf(addmsg, 32, "varmapack_testcase number %2d", icase);
    xCheckAddMsg(addmsg);

    // Query testcase dimensions and check them
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &pk, &qk, &rk, 0, 0, 0, 0);
    xCheck(!error);
    xCheck(pk == p);
    xCheck(qk == q);
    xCheck(rk == r);
    xCheck(h <= n);

    // Allocate and fetch actual testcase coefficients
    int r2 = r*r;
    ASSERT(ALLOC(A, r2*(p > 0 ? p : 1)), "allocation failed");
    ASSERT(ALLOC(B, r2*(q > 0 ? q : 1)), "allocation failed");
    ASSERT(ALLOC(Sig, r2), "allocation failed");
    STRSET(name, "");
    error = varmapack_testcase(name, &icase, 0, &p, &q, &r, A, B, Sig, 0);
    xCheck(!error);
    rhoC = varmapack_specrad(A, r, p);
    maRhoC = varmapack_ma_specrad(B, r, q);
    xCheck(fabs(rhoC - rhoMatlab) < 1e-12);
    xCheck(fabs(maRhoC - maRhoMatlab) < 1e-12);
    ASSERT(ALLOC(Gamma, r2*(acvfMaxlag+1)), "allocation failed");
    error = varmapack_acvf(A, B, Sig, p, q, r, Gamma, acvfMaxlag);
    xCheck(!error);
    ASSERT(ALLOC(Psi, r2*(acvfMaxlag+1)), "allocation failed");
    ASSERT(ALLOC(Theta, r2*(acvfMaxlag+1)), "allocation failed");
    error = varmapack_psi(A, B, p, q, r, acvfMaxlag, Psi);
    xCheck(!error);
    error = varmapack_irf(A, B, Sig, p, q, r, acvfMaxlag, Theta);
    xCheck(!error);

    // Compare A, B, Sig against MATLAB reference
    double diffA, diffB, diffSig, diffGamma, diffPsi, diffTheta;
    
    STRSETF(name, "A%d", label);   CompareWithMatlab(fid, name, A, r, r*p, &diffA);
    STRSETF(name, "B%d", label);   CompareWithMatlab(fid, name, B, r, r*q, &diffB);
    STRSETF(name, "Sig%d", label); CompareWithMatlab(fid, name, Sig, r, r, &diffSig);
    STRSETF(name, "Gamma-%d", icase);
    ok = CompareWithMatlab(fid, name, Gamma, r*r, acvfMaxlag+1, &diffGamma);
    STRSETF(name, "Psi-%d", icase);
    ok &= CompareWithMatlab(fid, name, Psi, r*r, acvfMaxlag+1, &diffPsi);
    STRSETF(name, "Theta-%d", icase);
    ok &= CompareWithMatlab(fid, name, Theta, r*r, acvfMaxlag+1, &diffTheta);
    xCheck(ok);
    xCheck(diffA < tol && diffB < tol && diffSig < tol && diffGamma < 5e-15);
    xCheck(diffPsi < 5e-15 && diffTheta < 5e-15);

    // Simulate with varmapack_sim and compare the simulated series with Matlab's
    for (int j=0; j<(int)nMs; j++) {
      int M = Ms[j];
      double *X = 0, *E = 0, *X0 = 0, *E0 = 0;
      double *Xmu = 0, *Emu = 0, *X0mu = 0, *E0mu = 0;
      double *Xpath = 0, *Epath = 0;
      double *AutoML = 0, *AutoC = 0;
      h = imax(p, q);
    
      ASSERT(ALLOC(X, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0, r*n*M), "allocation failed");
      ASSERT(ALLOC(Xmu, r*n*M), "allocation failed");
      ASSERT(ALLOC(X0mu, r*n*M), "allocation failed");
      ASSERT(ALLOC(E, r*n*M), "allocation failed");
      ASSERT(ALLOC(E0, r*n*M), "allocation failed");
      ASSERT(ALLOC(Emu, r*n*M), "allocation failed");
      ASSERT(ALLOC(E0mu, r*n*M), "allocation failed");
      ASSERT(ALLOC(Xpath, r*n*M), "allocation failed");
      ASSERT(ALLOC(Epath, r*n*M), "allocation failed");
      ASSERT(ALLOC(AutoML, r2*n), "allocation failed");
      ASSERT(ALLOC(AutoC, r2*n), "allocation failed");
      randompack_rng *rng = randompack_create(0);
      randompack_seed(42, 0, 0, rng);
      printM("A", A, r, r*p);
      printM("B", B, r, r*q);
      printM("Sig", Sig, r, r);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, M, 0, 0, 1, X, E, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, 0, 0, p, q, r, n, M, StartX0, h, 1, X0, E0, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, M, 0, 0, 1, Xmu, Emu, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, mu, 1, p, q, r, n, M, StartX0, h, 1, X0mu, E0mu, rng);
      xCheck(!error);
      randompack_seed(42, 0, 0, rng);
      error = varmapack_sim(A, B, Sig, muPath, 3, p, q, r, n, M, 0, 0, 1, Xpath, Epath, rng);
      xCheck(!error);
      error = varmapack_autocov("N", "ML", r, n, X, n-1, AutoML);
      xCheck(!error);
      error = varmapack_autocov("N", "C", r, n, X, n-1, AutoC);
      xCheck(!error);
      printM("X0", X0, r, n*M);
      // Compare E and X
      
      double diffE, diffX, diffE0, diffX0, diffEmu, diffXmu, diffE0mu, diffX0mu;
      double diffEpath, diffXpath, diffAutoML, diffAutoC;
      STRSETF(name, "AutoML%d-%d", M, icase);
      ok = CompareWithMatlab(fid, name, AutoML, r*r, n, &diffAutoML);
      STRSETF(name, "AutoC%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, AutoC, r*r, n, &diffAutoC);
      STRSETF(name, "E%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E, r*n, M, &diffE);
      STRSETF(name, "X%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X, r*n, M, &diffX);
      STRSETF(name, "E0%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E0, r*n, M, &diffE0);
      STRSETF(name, "X0%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0, r*n, M, &diffX0);
      STRSETF(name, "Emu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Emu, r*n, M, &diffEmu);
      STRSETF(name, "Xmu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Xmu, r*n, M, &diffXmu);
      STRSETF(name, "E0mu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, E0mu, r*n, M, &diffE0mu);
      STRSETF(name, "X0mu%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, X0mu, r*n, M, &diffX0mu);
      STRSETF(name, "Epath%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Epath, r*n, M, &diffEpath);
      STRSETF(name, "Xpath%d-%d", M, icase);
      ok &= CompareWithMatlab(fid, name, Xpath, r*n, M, &diffXpath);
      ASSERT(ok, "error comparing with Matlab");
      printD(">>> diffX", diffX);
      printD(">>> diffE", diffE);
      printD(">>> diffX0", diffX0);
      printD(">>> diffE0", diffE0);
      printD(">>> diffXmu", diffXmu);
      printD(">>> diffEmu", diffEmu);
      printD(">>> diffX0mu", diffX0mu);
      printD(">>> diffE0mu", diffE0mu);
      printD(">>> diffXpath", diffXpath);
      printD(">>> diffEpath", diffEpath);
      double simTol = sim_tol(r*n*M, rhoC);
      double autoTol = sim_tol(r2*n, rhoC);
      printD(">>> simulation tolerance", simTol);
      printD(">>> autocov tolerance", autoTol);
      check_norm_relative("E", icase, diffE, simTol);
      check_norm_relative("X", icase, diffX, simTol);
      check_norm_relative("AutoML", icase, diffAutoML, autoTol);
      check_norm_relative("AutoC", icase, diffAutoC, autoTol);
      check_norm_relative("Emu", icase, diffEmu, simTol);
      check_norm_relative("Xmu", icase, diffXmu, simTol);
      check_norm_relative("Epath", icase, diffEpath, simTol);
      check_norm_relative("Xpath", icase, diffXpath, simTol);
      if (pathwise_conditional_check(icase)) {
        check_norm_relative("X0", icase, diffX0, simTol);
        check_norm_relative("X0mu", icase, diffX0mu, simTol);
        check_norm_relative("E0", icase, diffE0, simTol);
        check_norm_relative("E0mu", icase, diffE0mu, simTol);
      }

      // Free memory
      FREE(AutoC);
      FREE(AutoML);
      FREE(Epath);
      FREE(Xpath);
      FREE(E0mu);
      FREE(X0mu);
      FREE(Emu);
      FREE(Xmu);
      FREE(E0);
      FREE(X0);
      FREE(E);
      FREE(X);
      randompack_free(rng);
    }
    FREE(A);
    FREE(B);
    FREE(Sig);
    FREE(Theta);
    FREE(Psi);
    FREE(Gamma);
    FREE(muPath);
    FREE(mu);
    FREE(StartX0);
    xCheckAddMsg("");
  }
  ok = compare_reduced_m(fid, n);
  xCheck(ok);
  ok = compare_rolling_matlab();
  xCheck(ok);
  ok = compare_varmax_matlab(fid, n, Ms, nMs);
  xCheck(ok);
  FREE(cases);
  FREE(Ms);
  fclose(fid);
  return true;
}
