// TestCompareWithMatlab.c
#include "ExtraUtil.h"
#include "allocate.h"
#include "xAssert.h"
#include "xCheck.h"
#include "printX.h"
#include "Tests.h"

#include "varmapack.h"
#include "varmapack.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

// Requires an include file generated by matlabcompare.m defining:
//   ncase, p[], q[], r[], n[], and pointer arrays A[], B[], Sig[], X[].
// ---------------------------------------------------------------------------
void TestAgainstMatlab(void) {
  // Bring in MATLAB reference data
#include "matlabcompare.inc"
  RandRng *rng = RandCreate();
  RandSetPM(rng);
  
  for (int icase = case1; icase <= caseN; icase++) {
    int pk, qk, rk, k = icase - case1;

    // Set additional message to testcase number
    char addmsg[32] = "varmapack_testcase number **";
    if (icase < 100) snprintf(addmsg, 32, "varmapack_testcase number %2d", icase);
    xCheckAddMsg(addmsg);

    // Query testcase dimensions and check them
    char name[64] = {0};
    bool ok = varmapack_testcase(0, 0, 0, name, &pk, &qk, &rk, &icase, 0, stderr);
    xCheck(ok);
    xCheck(pk == p[k]);
    xCheck(qk == q[k]);
    xCheck(rk == r[k]);
    
    // Allocate and fetch actual testcase coefficients
    int r2 = rk*rk, nk = n[k];
    int nA = pk > 0 ? r2*pk : 1;
    int nB = qk > 0 ? r2*qk : 1;
    double *Ak, *Bk, *Sigk;
    allocate(Ak, nA);
    allocate(Bk, nB);
    allocate(Sigk, r2);
    ok = varmapack_testcase(Ak, Bk, Sigk, name, &pk, &qk, &rk, &icase, 0, stderr);
    xCheck(ok);

    // Compare A, B, Sig against MATLAB reference
    xCheck(almostEqual(Ak, A[k], nA));
    xCheck(almostEqual(Bk, B[k], nB));
    xCheck(almostEqual(Sigk, Sig[k], r2));

    // Simulate with varmapack_sim and compare the simulated series with Matlab's
    double *mu = 0, *X0 = 0, *Xsim, *eps;
    int M = 1;
    bool sim_ok;
    allocate(Xsim, rk*nk);
    allocate(eps,  rk*nk);
    RandSeed(42, rng);
    printM("Ak", Ak, rk, rk*pk);
    printM("Bk", Bk, rk, rk*qk);
    printM("Sigk", Sigk, rk, rk);
    varmapack_sim(Ak, Bk, Sigk, mu, pk, qk, rk, nk, M, X0, 0, rng, Xsim, eps, &sim_ok);
    printSetNdec(15);
    printM("Xsim", Xsim, rk, nk);
    printSetNdec(3);
    xCheck(sim_ok == 1);
    xCheck(almostEqual(Xsim, X[k], rk*nk));

    // Free memory
    freem(Ak);
    freem(Bk);
    freem(Sigk);
    freem(Xsim);
    freem(eps);
  }
  xCheckAddMsg("");
}
