function build_varmapack_mex
  root = fileparts(fileparts(mfilename('fullpath')));
  rp = "/Users/jonasson/randompack";
  inc = fullfile(root, "src");
  lib = fullfile(root, "build", "src");
  rpinc = fullfile(rp, "src");
  rplib = fullfile(rp, "release", "src");
  mex("-I" + inc, "-I" + rpinc, "-L" + lib, "-lvarmapack", ...
      "-L" + rplib, "-lrandompack", ...
      "LDFLAGS=$LDFLAGS -Wl,-rpath," + lib + " -Wl,-rpath," + rplib, ...
      fullfile(root, "matlab", "varmapack_sim_gateway.c"), ...
      "-outdir", fullfile(root, "matlab"));
end
