test_that("VARMAX simulation accepts vector and replicate-specific exogenous inputs", {
  A <- array(c(0.2, 0, 0, 0.3), c(2L, 2L, 1L))
  B <- array(c(0.1, 0, 0, 0.2), c(2L, 2L, 1L))
  C <- array(c(0.3, 0.1, -0.2, 0.4), c(2L, 2L, 1L))
  model <- varmapack_model(A = A, B = B, C = C, Sig = diag(2))
  X0 <- array(0, c(2L, 2L, 2L))
  z <- array(seq_len(40)/10, c(2L, 10L, 2L))
  rng1 <- randompack::randompack_rng()
  rng2 <- randompack::randompack_rng()
  rng1$seed(99)
  rng2$seed(99)
  X1 <- model$sim(10, nrep = 2, X0 = X0, z = z, rng = rng1)
  X2 <- model$sim(10, nrep = 2, X0 = X0, z = z, rng = rng2)
  expect_identical(X1, X2)
  expect_equal(dim(X1), c(2L, 10L, 2L))
})

test_that("VARMAX simulation requires startup values and exogenous inputs", {
  model <- varmapack_model(C = matrix(0.3, 1, 1), Sig = matrix(1, 1, 1))
  expect_error(model$sim(10, z = matrix(0, 1, 10)))
  expect_error(model$sim(10, X0 = matrix(0, 1, 1)))
})
